apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: db_url
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my-cm
          key: db_user
