apiVersion: v1
kind: Pod
metadata:
  name: hostpath-mount
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/ubuntu/pod_data
      type: DirectoryOrCreate
